**https://www.youtube.com/watch?v=x9JiIFvlUwk&list=PLhhyoLH6IjfxeoooqP9rhU3HJIAVAJ3Vz&index=2**

In [ ]:
import torch

#**Initializing Tensors**

In [ ]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]])
my_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32, device="cpu")
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32, device="cpu", requires_grad=True)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"

my_tensor = torch.tensor([[1,2,3],[4,5,6]], device=device)
my_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.int64
cpu
torch.Size([2, 3])
False


In [ ]:
x = torch.empty(size=(3,3))
print(x)

tensor([[8.9358e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 6.4460e-44],
        [1.1578e+27, 1.1362e+30, 7.1547e+22]])


In [ ]:
x = torch.zeros(size=(3,3))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
x = torch.rand(size=(3,3))
print(x)

tensor([[0.8175, 0.9673, 0.1707],
        [0.8595, 0.0438, 0.0127],
        [0.4920, 0.5636, 0.7700]])


In [ ]:
x = torch.ones((3,3))
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
# Create identity matrix
x = torch.eye(5,5)
print(x)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [ ]:
x = torch.arange(start=0, end=5, step=2)
print(x)

tensor([0, 2, 4])


In [ ]:
x = torch.linspace(start=0.1, end=1, steps=10)
print(x)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [ ]:
# Normal Distribution
x = torch.empty((1,5)).normal_(mean=0, std=1)
print(x)

tensor([[-0.2373, -0.2966, -0.5860, -1.1551,  0.6122]])


In [ ]:
# Uniform Distribution
x = torch.empty((1,5)).uniform_(0,1)
print(x)

tensor([[0.8978, 0.1310, 0.2050, 0.1942, 0.5445]])


In [ ]:
x = torch.diag(torch.ones(3))
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [ ]:
tensor = torch.arange(4)

In [ ]:
print(tensor.bool())

tensor([False,  True,  True,  True])


In [ ]:
print(tensor.short())

tensor([0, 1, 2, 3], dtype=torch.int16)


In [ ]:
print(tensor.long())

tensor([0, 1, 2, 3])


In [ ]:
print(tensor.half())

tensor([0., 1., 2., 3.], dtype=torch.float16)


In [ ]:
print(tensor.float())

tensor([0., 1., 2., 3.])


In [ ]:
print(tensor.double())

tensor([0., 1., 2., 3.], dtype=torch.float64)


In [ ]:
import numpy as np

In [ ]:
np_array = np.zeros((5,5))
print(np_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
tensor = torch.from_numpy(np_array)
print(tensor)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)


In [ ]:
np_array_back = tensor.numpy()
print(np_array_back)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#**Tensors Math**

In [ ]:
import torch

In [ ]:
X = torch.tensor([1,2,3])
Y = torch.tensor([9,8,7])

In [ ]:
# Addition

z1 = torch.empty(3)
torch.add(X,Y,out=z1)
print(z1)

tensor([10., 10., 10.])


In [ ]:
hh = torch.add(X, Y)
print(hh)

tensor([10, 10, 10])


In [ ]:
z = X + Y
print(z)

tensor([10, 10, 10])


In [ ]:
# Subtraction

Z = X - Y
print(Z)

tensor([-8, -6, -4])


In [ ]:
# Division

z = torch.true_divide(X, Y)
print(z)

tensor([0.1111, 0.2500, 0.4286])


In [ ]:
# Inplace Operations

t = torch.zeros(3)
t.add_(X)
print(t)

tensor([1., 2., 3.])


In [ ]:
t += X
print(t)

tensor([2., 4., 6.])


In [ ]:
# Exponentiation

q = X.pow(2)
print(q)

tensor([1, 4, 9])


In [ ]:
q = X ** 2
print(q)

tensor([1, 4, 9])


In [ ]:
# Simple Comparison

X = torch.tensor([1,2,3])
z = X > 0
print(z)

tensor([True, True, True])


In [ ]:
z = X < 0
print(z)

tensor([False, False, False])


In [ ]:
# Matrix Multiplication

x1 = torch.rand((2,5))
x2 = torch.rand((5,3))

In [ ]:
x3 = torch.mm(x1, x2)   #2x3
print(x3)

tensor([[0.8541, 0.5507, 0.7314],
        [1.3763, 0.7735, 1.2126]])


In [ ]:
x3 = x1.mm(x2)
print(x3)

tensor([[0.8541, 0.5507, 0.7314],
        [1.3763, 0.7735, 1.2126]])


In [ ]:
#Matrix Exponentiation

matrix_exp = torch.rand(5, 5)
print(matrix_exp.matrix_power(3))

tensor([[1.7943, 1.5111, 1.1928, 1.6369, 1.6089],
        [1.5298, 1.3500, 1.1307, 1.6705, 1.5293],
        [1.6945, 1.6108, 1.3173, 2.0423, 1.6526],
        [3.0970, 2.3113, 1.6987, 3.0858, 2.8877],
        [0.8312, 0.9028, 0.7586, 1.0128, 0.7750]])


In [ ]:
# Element wise Multiplication

z = X * Y
print(z)

tensor([ 9, 16, 21])


In [ ]:
# Dot product

z = torch.dot(X, Y)
print(z)

tensor(46)


In [ ]:
# Batch Matrix Multiplication

batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2)  #(batch, n, p)
print(out_bmm)

tensor([[[4.3763, 4.6135, 4.7604,  ..., 6.7489, 4.8208, 5.7158],
         [4.3793, 5.3472, 4.9082,  ..., 7.3833, 4.7334, 6.4695],
         [5.1190, 6.4262, 6.3802,  ..., 8.0992, 5.1039, 5.9865],
         ...,
         [5.1868, 6.6413, 6.2710,  ..., 8.5074, 5.3298, 7.0581],
         [5.4203, 5.8460, 6.0576,  ..., 6.9973, 5.1281, 7.0818],
         [3.9919, 4.6582, 4.5026,  ..., 5.6491, 4.1257, 4.8821]],

        [[4.3048, 4.2359, 4.4652,  ..., 4.0329, 4.3132, 4.4289],
         [4.1080, 4.5493, 4.4643,  ..., 4.4919, 4.5301, 4.8112],
         [4.8794, 4.5103, 4.6266,  ..., 4.6877, 5.4990, 4.5955],
         ...,
         [4.4805, 4.4698, 4.8057,  ..., 4.9211, 5.0030, 5.0066],
         [5.7269, 5.1618, 4.4146,  ..., 4.9560, 5.5793, 5.2797],
         [5.1849, 5.1401, 4.9428,  ..., 5.2249, 5.0841, 5.6136]],

        [[4.7324, 4.4914, 3.6992,  ..., 4.7794, 6.0940, 3.4205],
         [5.6321, 6.6316, 5.0823,  ..., 5.1758, 6.9106, 4.2252],
         [6.1526, 6.8080, 5.6338,  ..., 5.5026, 7.1351, 4.

In [ ]:
#Example of Broadcasting

x1 = torch.rand((5,5))
x2 = torch.rand((1,5))

z = x1 - x2
print(z)
z = x1 ** x2
print(z)

tensor([[ 0.0969,  0.5926,  0.2205, -0.0781,  0.7504],
        [ 0.2103,  0.7063, -0.6143, -0.0277,  0.1495],
        [-0.0498,  0.4703, -0.1511, -0.1517,  0.2180],
        [-0.2874,  0.5108,  0.0836, -0.2196,  0.9643],
        [-0.6023,  0.5791, -0.4289, -0.2908,  0.5794]])
tensor([[0.8078, 0.9905, 0.9533, 0.7405, 0.9992],
        [0.8845, 0.9938, 0.1934, 0.7818, 0.9945],
        [0.7010, 0.9862, 0.6638, 0.6788, 0.9956],
        [0.5001, 0.9877, 0.8513, 0.6200, 0.9999],
        [0.0358, 0.9901, 0.4086, 0.5564, 0.9984]])


In [ ]:
# Oher useful tensor operations
sum_x = torch.sum(X, dim=0)
print(sum_x)

values, indices = torch.max(X, dim=0)
print(values, indices)

values, indices = torch.min(X, dim=0)
print(values, indices)

abs_x = torch.abs(x)
print(abs_x)

z = torch.argmax(X, dim=0)
print(z)

z = torch.argmin(X, dim=0)
print(z)

mean_x = torch.mean(X.float(), dim=0)
print(mean_x)

z = torch.eq(X, Y)
print(z)

tensor(6)
tensor(3) tensor(2)
tensor(1) tensor(0)
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor(2)
tensor(0)
tensor(2.)
tensor([False, False, False])


In [ ]:
z = torch.sort(Y, dim=0, descending=False)
print(z)

torch.return_types.sort(
values=tensor([7, 8, 9]),
indices=tensor([2, 1, 0]))


In [ ]:
z = torch.sort(Y, dim=0, descending=True)
print(z)

torch.return_types.sort(
values=tensor([9, 8, 7]),
indices=tensor([0, 1, 2]))


In [ ]:
sorted_y, indices = torch.sort(Y, dim=0, descending=False)
print(sorted_y, indices)

tensor([7, 8, 9]) tensor([2, 1, 0])


In [ ]:
z = torch.clamp(X, min=0)
print(z)

tensor([1, 2, 3])


In [ ]:
z = torch.clamp(X, min=0, max=10)
print(z)

tensor([1, 2, 3])


In [ ]:
x = torch.tensor([1,0,1,1,1], dtype=bool)
z = torch.any(x)
print(z)
z = torch.all(x)  # False because we have one value zero
print(z)

tensor(True)
tensor(False)


#**Tensor Indexing**

In [ ]:
batch_size = 10
features= 25
x = torch.rand((batch_size, features))
print(x)

tensor([[0.8822, 0.5414, 0.9343, 0.0632, 0.7608, 0.6984, 0.6106, 0.7327, 0.0521,
         0.1385, 0.3161, 0.9622, 0.8123, 0.8783, 0.2589, 0.5449, 0.9595, 0.2149,
         0.4296, 0.5803, 0.6797, 0.6718, 0.2577, 0.9579, 0.8483],
        [0.2821, 0.8433, 0.4888, 0.6914, 0.2174, 0.3989, 0.9409, 0.7723, 0.5232,
         0.0862, 0.1166, 0.4904, 0.5769, 0.7307, 0.6133, 0.2907, 0.5363, 0.9674,
         0.1348, 0.1447, 0.5733, 0.1687, 0.6875, 0.3650, 0.4507],
        [0.2735, 0.7640, 0.3049, 0.2083, 0.0193, 0.3754, 0.8138, 0.4909, 0.3905,
         0.9717, 0.3684, 0.4263, 0.3284, 0.8749, 0.4941, 0.0043, 0.9295, 0.4729,
         0.6580, 0.4806, 0.3642, 0.6197, 0.9683, 0.9340, 0.2033],
        [0.6441, 0.3089, 0.0856, 0.5330, 0.0380, 0.0342, 0.8170, 0.5134, 0.8366,
         0.4035, 0.6056, 0.8207, 0.1887, 0.0998, 0.0543, 0.2317, 0.6848, 0.1390,
         0.2500, 0.5678, 0.6323, 0.0175, 0.4615, 0.1765, 0.8415],
        [0.6464, 0.4039, 0.9228, 0.9341, 0.7630, 0.1756, 0.1565, 0.9805, 0.7228,
       

In [ ]:
print(x[0])

tensor([0.8822, 0.5414, 0.9343, 0.0632, 0.7608, 0.6984, 0.6106, 0.7327, 0.0521,
        0.1385, 0.3161, 0.9622, 0.8123, 0.8783, 0.2589, 0.5449, 0.9595, 0.2149,
        0.4296, 0.5803, 0.6797, 0.6718, 0.2577, 0.9579, 0.8483])


In [ ]:
print(x[0].shape)  #x[0,:]

torch.Size([25])


In [ ]:
print(x[:,0])
print(x[:,0].shape)

tensor([0.8822, 0.2821, 0.2735, 0.6441, 0.6464, 0.5186, 0.7780, 0.7057, 0.1810,
        0.6913])
torch.Size([10])


In [ ]:
print(x[2, 0:10])
print(x[2, 0:10].shape)

tensor([0.2735, 0.7640, 0.3049, 0.2083, 0.0193, 0.3754, 0.8138, 0.4909, 0.3905,
        0.9717])
torch.Size([10])


In [ ]:
x[0, 0] = 100

In [ ]:
# Fancy Indexing
x = torch.arange(10)
indices = [2,5,8]
print(x[indices])

tensor([2, 5, 8])


In [ ]:
x = torch.rand(3,5)
rows = torch.tensor([1,0])
cols = torch.tensor([4,0])
print(x[rows, cols])
print(x[rows, cols].shape)

tensor([0.9654, 0.5143])
torch.Size([2])


In [ ]:
# More advanced indexing
x = torch.arange(10)
print(x[(x < 2) | (x > 8)])
print(x[(x < 2) & (x > 8)])
print(x[(x < 2) ^ (x > 8)])

tensor([0, 1, 9])
tensor([], dtype=torch.int64)
tensor([0, 1, 9])


In [ ]:
print(x[x.remainder(2) == 0])

tensor([0, 2, 4, 6, 8])


In [ ]:
# Other useful operations
print(torch.where(x > 5, x, x*2))

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])


In [ ]:
print(torch.tensor([0,0,1,1,1,2,2,2,2]).unique())

tensor([0, 1, 2])


In [ ]:
print(x.ndimension())  #5x5x5
print(x.numel())

1
10


#**Tensors Reshaping**

In [89]:
x = torch.arange(9)

In [91]:
x_3x3 = x.view(3, 3)
print(x_3x3)
print(x_3x3.shape)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
torch.Size([3, 3])


In [93]:
x_3x3 = x.reshape(3, 3)
print(x_3x3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [95]:
y = x_3x3.t()
print(y)
print(y.contiguous().view(9))

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


In [97]:
x1 = torch.rand(2, 5)
x2 = torch.rand(2, 5)
print(torch.cat((x1, x2), dim=0).shape)
print(torch.cat((x1, x2), dim=1).shape)

torch.Size([4, 5])
torch.Size([2, 10])


In [98]:
z = x1.view(-1)
print(z)
print(z.shape)

tensor([0.0990, 0.3900, 0.0223, 0.4956, 0.5875, 0.4536, 0.6881, 0.5932, 0.6112,
        0.1472])
torch.Size([10])


In [100]:
batch = 64
x = torch.rand((batch, 2, 5))
z = x.view(batch, -1)

#print(x)
print(x.shape)

#print(z)
print(z.shape)

torch.Size([64, 2, 5])
torch.Size([64, 10])


In [102]:
z = x.permute(0, 2, 1)
#print(z)
print(z.shape)

torch.Size([64, 5, 2])


In [104]:
x = torch.arange(10)
print(x.unsqueeze(0))
print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
torch.Size([1, 10])
torch.Size([10, 1])


In [105]:
x = torch.arange(10).unsqueeze(0).unsqueeze(1)

z = x.squeeze(1)
print(z)
print(z.shape)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
torch.Size([1, 10])
